In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.font_manager as fm
import numpy as np 
import seaborn as sns 
import folium
from datetime import datetime, timedelta

import pandas as pd
import geopandas as gpd
import plotly.express as px
import plotly.graph_objects as go

In [2]:
# load excel dataset
raw_data = pd.read_excel(
    '/Users/tish/Documents/Flexible Masters/02806 - Social data and visualization/CODE_Social_data_Visialization/TishDuc.github.io/Displacements_Final_Project/Data/UNHCR_Flow_Data.xlsx',
    sheet_name='DATA'
)

# display the first 10 rows of the dataset
raw_data[:10]

,origin,OriginISO,OriginName,asylum,AsylumISO,AsylumName,AsylumRegion,Population types,Year,Count
0,ALG,DZA,Algeria,MTA,MLT,Malta,Europe,REF,1962,5
1,ANG,AGO,Angola,COD,COD,Dem. Rep. of the Congo,West and Central Africa,REF,1962,20000
2,ANG,AGO,Angola,NAM,NAM,Namibia,Eastern and Southern Africa,REF,1962,277
3,BDI,BDI,Burundi,NAM,NAM,Namibia,Eastern and Southern Africa,REF,1962,13
4,CHI,CHN,China,NEP,NPL,Nepal,Asia and the Pacific,REF,1962,5
5,COB,COG,"Congo, Republic of",NAM,NAM,Namibia,Eastern and Southern Africa,REF,1962,8
6,COD,COD,Dem. Rep. of the Congo,NAM,NAM,Namibia,Eastern and Southern Africa,REF,1962,13
7,IRQ,IRQ,Iraq,MTA,MLT,Malta,Europe,REF,1962,17
8,SOM,SOM,Somalia,NAM,NAM,Namibia,Eastern and Southern Africa,REF,1962,5
9,SUD,SDN,Sudan,MTA,MLT,Malta,Europe,REF,1962,10

In [3]:
print(raw_data.shape)

(107341, 10)

In [4]:
# -------------------------------------------------------------------
#                      changes to the raw data 
# -------------------------------------------------------------------

#    lower casing
# ------------------
# header to lowercase
raw_data.columns = raw_data.columns.str.lower()
# data to lowercase
for col in raw_data.select_dtypes(include='object'):
    raw_data[col] = raw_data[col].str.lower()

# check for duplicates
# ---------------------
print("number of duplicates found:", raw_data.duplicated().sum()) # ----> 0 duplicates

# check for missing values
# ---------------------
print(raw_data.isnull().sum()) 
# show rows with missing values
# print(raw_data[raw_data.isnull().any(axis=1)])
# remove rows with missing values
raw_data = raw_data.dropna()


# Sanity check it worked:
# ---------------------
# print(raw_data.isnull().sum())
raw_data[:20]

number of duplicates found: 0
origin               0
originiso            0
originname          35
asylum               0
asylumiso            0
asylumname           0
asylumregion        37
population types     0
year                 0
count                0
dtype: int64

,origin,originiso,originname,asylum,asylumiso,asylumname,asylumregion,population types,year,count
0,alg,dza,algeria,mta,mlt,malta,europe,ref,1962,5
1,ang,ago,angola,cod,cod,dem. rep. of the congo,west and central africa,ref,1962,20000
2,ang,ago,angola,nam,nam,namibia,eastern and southern africa,ref,1962,277
3,bdi,bdi,burundi,nam,nam,namibia,eastern and southern africa,ref,1962,13
4,chi,chn,china,nep,npl,nepal,asia and the pacific,ref,1962,5
5,cob,cog,"congo, republic of",nam,nam,namibia,eastern and southern africa,ref,1962,8
6,cod,cod,dem. rep. of the congo,nam,nam,namibia,eastern and southern africa,ref,1962,13
7,irq,irq,iraq,mta,mlt,malta,europe,ref,1962,17
8,som,som,somalia,nam,nam,namibia,eastern and southern africa,ref,1962,5
9,sud,sdn,sudan,mta,mlt,malta,europe,ref,1962,10
11,ang,ago,angola,cod,cod,dem. rep. of the congo,west and central africa,ref,1963,5000
12,are,egy,egypt,leb,lbn,lebanon,middle east and north africa,ref,1963,160
13,rom,rou,romania,leb,lbn,lebanon,middle east and north africa,ref,1963,70
14,rwa,rwa,rwanda,bdi,bdi,burundi,eastern and southern africa,ref,1963,4000
15,rwa,rwa,rwanda,cod,cod,dem. rep. of the congo,west and central africa,ref,1963,1000
16,rwa,rwa,rwanda,uga,uga,uganda,eastern and southern africa,ref,1963,2000
17,sud,sdn,sudan,cod,cod,dem. rep. of the congo,west and central africa,ref,1963,8000
18,sud,sdn,sudan,uga,uga,uganda,eastern and southern africa,ref,1963,5000
20,ang,ago,angola,cod,cod,dem. rep. of the congo,west and central africa,ref,1964,25000
21,arm,arm,armenia,are,egy,egypt,middle east and north africa,ref,1964,90

In [ ]:
# deal with annoyinhg names????

"Côte d'Ivoire", "Iran (Islamic Rep. of)", "Netherlands (Kingdom of the)", "State of Palestine", 
"Lao People's Dem. Rep" = "Laos"

"Dem. Rep. of the Congo" VS "Congo, Republic of"

In [5]:
# --------------------------------------------------------------
#                      Export cleaned Data
# --------------------------------------------------------------

# export cleaned data to csv
raw_data.to_csv('/Users/tish/Documents/Flexible Masters/02806 - Social data and visualization/CODE_Social_data_Visialization/TishDuc.github.io/Displacements_Final_Project/Data/cleaned_data.csv', index=False)